
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'
import { Providers } from './redux/providers'


export const metadata = {
  title: 'Rent app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
        {/* Main content */}       
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
